name: k6-smoke
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p out
      - uses: grafana/setup-k6-action@v1

      - name: Run open_only (fast)
        env:
          BASE_URL: https://www.wikipedia.org/
          THINK_TIME_SEC: "1"
        run: |
          k6 run tests/performance/k6/kds_open_only.js \
            -e BASE_URL="$BASE_URL" \
            -e THINK_TIME_SEC="$THINK_TIME_SEC" \
            --summary-export out/smoke_open_only.summary.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: out/**
          if-no-files-found: warn